version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
    command: python src/main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test
    volumes:
      - .:/app
    command: pytest src/tests
